### ISSUE TITLE
RSS feed links use incorrect domain

### ISSUE THREAD

**Issue by rianoc-kx** [DefconQ/defconQ#1]
Hi,

I've tried to use the RSS feed on your blog at: https://defconq.tech/blog/rss.xml

But it links to your articles using urls like:
* https://defconq.github.io/blog/DefconQ%20at%20Everything,%20Everywhere,%20All%20with%20KDB/Q%20by%20Habla%20Computing

But that is a dead link as it should be:
* https://www.defconq.tech/blog/DefconQ%20at%20Everything,%20Everywhere,%20All%20with%20KDB/Q%20by%20Habla%20Computing

Possibly it could be down to:
https://github.com/DefconQ/defconQ/blob/master/my-website/docusaurus.config.ts#L11

```
url: 'https://DefconQ.github.io',
```

**Comment by DefconQ** [comment]
Hi @rianoc-kx, thanks for pointing this out, I tried your fix but it keeps throwing below error. I tried to ask on the Docusaurus GitHub page here https://github.com/facebook/docusaurus/discussions/10027 but no luck. 

`
[ERROR] Error: Unable to build website for locale en.
    at tryToBuildLocale (/Users/Alexander/repos/defconQ/my-website/node_modules/@docusaurus/core/lib/commands/build.js:53:19)
    at async /Users/Alexander/repos/defconQ/my-website/node_modules/@docusaurus/core/lib/commands/build.js:64:9
    at async mapAsyncSequential (/Users/Alexander/repos/defconQ/my-website/node_modules/@docusaurus/utils/lib/jsUtils.js:20:24)
    at async Command.build (/Users/Alexander/repos/defconQ/my-website/node_modules/@docusaurus/core/lib/commands/build.js:62:5) {
  [cause]: TypeError: Cannot destructure property 'url' of 'siteConfig' as it is undefined.
      at defaultCreateFeedItems (/Users/Alexander/repos/defconQ/my-website/node_modules/@docusaurus/plugin-content-blog/lib/feed.js:54:18)
      at createFeedItems (/Users/Alexander/repos/defconQ/my-website/docusaurus.config.ts:52:18)
      at generateBlogFeed (/Users/Alexander/repos/defconQ/my-website/node_modules/@docusaurus/plugin-content-blog/lib/feed.js:44:29)
      at createBlogFeedFiles (/Users/Alexander/repos/defconQ/my-website/node_modules/@docusaurus/plugin-content-blog/lib/feed.js:136:24)
      at Object.postBuild (/Users/Alexander/repos/defconQ/my-website/node_modules/@docusaurus/plugin-content-blog/lib/index.js:330:50)
      at /Users/Alexander/repos/defconQ/my-website/node_modules/@docusaurus/core/lib/commands/build.js:170:22
      at Array.map (<anonymous>)
      at executePluginsPostBuild (/Users/Alexander/repos/defconQ/my-website/node_modules/@docusaurus/core/lib/commands/build.js:166:31)
      at /Users/Alexander/repos/defconQ/my-website/node_modules/@docusaurus/core/lib/commands/build.js:134:57
      at Object.async (/Users/Alexander/repos/defconQ/my-website/node_modules/@docusaurus/core/lib/utils.js:36:47)
      at buildLocale (/Users/Alexander/repos/defconQ/my-website/node_modules/@docusaurus/core/lib/commands/build.js:134:30)
      at async tryToBuildLocale (/Users/Alexander/repos/defconQ/my-website/node_modules/@docusaurus/core/lib/commands/build.js:46:13)
      at async /Users/Alexander/repos/defconQ/my-website/node_modules/@docusaurus/core/lib/commands/build.js:64:9
      at async mapAsyncSequential (/Users/Alexander/repos/defconQ/my-website/node_modules/@docusaurus/utils/lib/jsUtils.js:20:24)
      at async Command.build (/Users/Alexander/repos/defconQ/my-website/node_modules/@docusaurus/core/lib/commands/build.js:62:5)
}
[INFO] Docusaurus version: 3.2.1
Node version: v20.5.1
error Command failed with exit code 1.`
